/*
 * This Spock specification was generated by the Gradle 'init' task.
 */


import spock.lang.Specification

import java.time.LocalDateTime
import java.time.format.DateTimeFormatterBuilder

class BranchySpec extends Specification {
    def tmpBaseFolder

    def setup() {
        def now = LocalDateTime.now()
        def formatter = DateTimeFormatterBuilder.newInstance().appendPattern('yyyy-MM-dd_hh-mm-ss').toFormatter()

        def tmpRunFolder = new File('/tmp/branchy/' + formatter.format(now))
        tmpRunFolder.mkdirs()

        println 'base folder for tests to store data on disk: ' + tmpRunFolder
    }

    def "someLibraryMethod returns true"() {
        when:
//        println 'ls'.execute().text

        then:
        true
    }

    def getPath2Tool() {
        return '../'
    }
}
